name    'treydock-ssh'
version '1.0.0'
source 'git://github.com/treydock/puppet-ssh.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'ssh module'
description 'ssh module'
project_page 'http://github.com/treydock/puppet-ssh'
dependency 'puppetlabs/stdlib', '>=3.2.0'
dependency 'domcleal/augeasproviders', '>=1.0.2'
